-- ============================================================
--  Miralocks — SETUP COMPLET + SÉCURITÉ
--  Version : 7.0 — Généré le 09/04/2026
--
--  INSTRUCTIONS :
--  1. Ouvrez Supabase Dashboard → SQL Editor → New query
--  2. Copiez-collez tout ce fichier
--  3. Cliquez sur "Run"
--
--  Ce script fait tout en une seule fois :
--  ✅ Crée toutes les tables
--  ✅ Configure les permissions
--  ✅ Active le RLS (sécurité)
--  ✅ Corrige les failles de sécurité (clés API, 2FA, etc.)
--  ✅ Crée les triggers anti-spam
--  ✅ Crée les index de performance
-- ============================================================


-- ══════════════════════════════════════════════════════════════
-- 1. TABLES
-- ══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.settings (
  cle        TEXT PRIMARY KEY,
  valeur     TEXT,
  modifie_le TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.site_settings (
  id         TEXT PRIMARY KEY,
  valeur     TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.blog_posts (
  id         BIGSERIAL PRIMARY KEY,
  titre      TEXT NOT NULL,
  extrait    TEXT,
  contenu    TEXT,
  photo_url  TEXT,
  categorie  TEXT DEFAULT 'Conseil',
  slug       TEXT,
  publie     BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.galerie_photos (
  id          BIGSERIAL PRIMARY KEY,
  titre       TEXT,
  description TEXT,
  photo_url   TEXT NOT NULL,
  categorie   TEXT DEFAULT 'creation',
  ordre       INTEGER DEFAULT 0,
  publie      BOOLEAN DEFAULT true,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);


CREATE TABLE IF NOT EXISTS public.avis_clients (
  id         BIGSERIAL PRIMARY KEY,
  nom        TEXT NOT NULL,
  localite   TEXT DEFAULT 'Lomé, Togo',
  etoiles    SMALLINT DEFAULT 5 CHECK (etoiles >= 1 AND etoiles <= 5),
  texte      TEXT NOT NULL,
  approuve   BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.services (
  id          BIGSERIAL PRIMARY KEY,
  nom         TEXT NOT NULL,
  description TEXT,
  prix        TEXT,
  categorie   TEXT DEFAULT 'Autres',
  ordre       INTEGER DEFAULT 0,
  actif       BOOLEAN DEFAULT true,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.rendezvous (
  id                 BIGSERIAL PRIMARY KEY,
  nom                TEXT NOT NULL,
  tel                TEXT NOT NULL,
  email              TEXT,
  service            TEXT NOT NULL,
  date_rdv           DATE NOT NULL,
  heure              TEXT,
  message            TEXT,
  photo_url          TEXT,
  statut             TEXT DEFAULT 'en_attente'
                     CHECK (statut IN ('en_attente','confirme','annule','termine')),
  note_admin         TEXT,
  whatsapp_callmebot TEXT,
  callmebot_apikey   TEXT,
  pay_acompte        BOOLEAN DEFAULT false,
  acompte_montant    INTEGER DEFAULT 0,
  transaction_id     TEXT,
  created_at         TIMESTAMPTZ DEFAULT NOW()
);

-- Migration : ajouter les colonnes si la table existe déjà
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='rendezvous' AND column_name='pay_acompte') THEN
    ALTER TABLE public.rendezvous ADD COLUMN pay_acompte BOOLEAN DEFAULT false;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='rendezvous' AND column_name='acompte_montant') THEN
    ALTER TABLE public.rendezvous ADD COLUMN acompte_montant INTEGER DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='rendezvous' AND column_name='transaction_id') THEN
    ALTER TABLE public.rendezvous ADD COLUMN transaction_id TEXT;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.admin_2fa (
  id         BIGSERIAL PRIMARY KEY,
  email      TEXT NOT NULL,
  code       TEXT NOT NULL,
  attempts   INTEGER DEFAULT 0,
  used       BOOLEAN DEFAULT false,
  expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '10 minutes'),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.admin_logs (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_email TEXT,
  action     TEXT NOT NULL,
  details    TEXT
);

CREATE TABLE IF NOT EXISTS public.historique (
  id         BIGSERIAL PRIMARY KEY,
  type       TEXT NOT NULL,
  message    TEXT NOT NULL,
  detail     TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.visites (
  id         BIGSERIAL PRIMARY KEY,
  page       TEXT NOT NULL DEFAULT '/',
  referrer   TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);


-- ══════════════════════════════════════════════════════════════
-- 2. PERMISSIONS (GRANTS)
-- ══════════════════════════════════════════════════════════════

-- Accès au schéma public
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT USAGE ON SCHEMA public TO postgres;

-- Accès public (lecture seule pour les tables non-sensibles)
GRANT SELECT, INSERT ON public.avis_clients TO anon;
GRANT USAGE, SELECT ON SEQUENCE avis_clients_id_seq TO anon;
GRANT SELECT ON public.blog_posts           TO anon;
GRANT SELECT ON public.galerie_photos       TO anon;
GRANT SELECT ON public.services             TO anon;
GRANT INSERT ON public.visites              TO anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;

-- ⚠️ SÉCURITÉ : NE PAS donner SELECT sur settings/site_settings à anon
-- (contient les clés API de paiement)
REVOKE SELECT ON public.settings      FROM anon;
REVOKE SELECT ON public.site_settings FROM anon;

-- ⚠️ SÉCURITÉ : rendezvous — anon peut seulement insérer, pas lire
REVOKE SELECT ON public.rendezvous FROM anon;
GRANT INSERT ON public.rendezvous TO anon;
GRANT USAGE, SELECT ON SEQUENCE rendezvous_id_seq TO anon;

-- ⚠️ SÉCURITÉ : historique — anon ne peut pas écrire
REVOKE INSERT ON public.historique FROM anon;

-- ⚠️ SÉCURITÉ : admin_2fa et admin_logs — aucun accès anon
REVOKE ALL ON public.admin_2fa  FROM anon;
REVOKE ALL ON public.admin_logs FROM anon;

-- Accès total pour l'admin authentifié
GRANT ALL ON ALL TABLES    IN SCHEMA public TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;


-- ══════════════════════════════════════════════════════════════
-- 3. ROW LEVEL SECURITY (RLS)
-- ══════════════════════════════════════════════════════════════

ALTER TABLE public.blog_posts     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.galerie_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.avis_clients   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rendezvous     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_logs     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_2fa      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.historique     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visites        ENABLE ROW LEVEL SECURITY;


-- Blog
DROP POLICY IF EXISTS "read_public_blog" ON public.blog_posts;
DROP POLICY IF EXISTS "admin_all_blog"   ON public.blog_posts;
CREATE POLICY "read_public_blog" ON public.blog_posts
  FOR SELECT USING (publie = true);
CREATE POLICY "admin_all_blog" ON public.blog_posts
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Galerie photos
DROP POLICY IF EXISTS "read_public_galerie" ON public.galerie_photos;
DROP POLICY IF EXISTS "admin_all_galerie"   ON public.galerie_photos;
CREATE POLICY "read_public_galerie" ON public.galerie_photos
  FOR SELECT USING (publie = true);
CREATE POLICY "admin_all_galerie" ON public.galerie_photos
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Avis clients
DROP POLICY IF EXISTS "read_public_avis"   ON public.avis_clients;
DROP POLICY IF EXISTS "insert_public_avis" ON public.avis_clients;
DROP POLICY IF EXISTS "admin_all_avis"     ON public.avis_clients;
CREATE POLICY "read_public_avis" ON public.avis_clients
  FOR SELECT USING (approuve = true);
CREATE POLICY "insert_public_avis" ON public.avis_clients
  FOR INSERT WITH CHECK (true);
CREATE POLICY "admin_all_avis" ON public.avis_clients
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Rendez-vous (anon peut seulement soumettre, pas lire)
DROP POLICY IF EXISTS "insert_public_rdv" ON public.rendezvous;
DROP POLICY IF EXISTS "admin_all_rdv"     ON public.rendezvous;
CREATE POLICY "insert_public_rdv" ON public.rendezvous
  FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "admin_all_rdv" ON public.rendezvous
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Services
DROP POLICY IF EXISTS "public_read_services"     ON public.services;
DROP POLICY IF EXISTS "admin_all_services_total" ON public.services;
CREATE POLICY "public_read_services" ON public.services
  FOR SELECT USING (true);
CREATE POLICY "admin_all_services_total" ON public.services
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Settings (clés API — admin seulement)
DROP POLICY IF EXISTS "read_public_settings" ON public.settings;
DROP POLICY IF EXISTS "admin_all_settings"   ON public.settings;
DROP POLICY IF EXISTS "admin_read_settings"  ON public.settings;
DROP POLICY IF EXISTS "admin_write_settings" ON public.settings;
CREATE POLICY "admin_read_settings" ON public.settings
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "admin_write_settings" ON public.settings
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Site settings (whitelist des clés non-sensibles pour anon)
DROP POLICY IF EXISTS "read_public_site_settings"     ON public.site_settings;
DROP POLICY IF EXISTS "admin_all_site_settings"       ON public.site_settings;
DROP POLICY IF EXISTS "anon_read_public_site_settings" ON public.site_settings;
CREATE POLICY "anon_read_public_site_settings" ON public.site_settings
  FOR SELECT TO anon
  USING (
    id NOT IN (
      'cinetpay_apikey',
      'cinetpay_siteid',
      'fedapay_apikey',
      'kkiapay_publickey',
      'paygate_apikey',
      'callmebot_apikey',
      'whatsapp_callmebot',
      'admin_email',
      'admin_password',
      'smtp_password',
      'smtp_user'
    )
  );
CREATE POLICY "admin_all_site_settings" ON public.site_settings
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Admin 2FA (codes OTP — Edge Function via service_role + admin authentifié)
DROP POLICY IF EXISTS "admin_only_2fa" ON public.admin_2fa;
-- service_role bypasse automatiquement le RLS → Edge Functions OK
-- authenticated = accès admin depuis le dashboard
CREATE POLICY "admin_only_2fa" ON public.admin_2fa
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Logs admin
DROP POLICY IF EXISTS "Admins can do everything on logs" ON public.admin_logs;
DROP POLICY IF EXISTS "admin_only_logs"                  ON public.admin_logs;
CREATE POLICY "admin_only_logs" ON public.admin_logs
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Historique (admin seulement)
DROP POLICY IF EXISTS "admin_all_historique"     ON public.historique;
DROP POLICY IF EXISTS "public_insert_historique" ON public.historique;
CREATE POLICY "admin_all_historique" ON public.historique
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Visites
DROP POLICY IF EXISTS "insert_public_visite" ON public.visites;
DROP POLICY IF EXISTS "admin_read_visites"   ON public.visites;
CREATE POLICY "insert_public_visite" ON public.visites
  FOR INSERT WITH CHECK (true);
CREATE POLICY "admin_read_visites" ON public.visites
  FOR SELECT TO authenticated USING (true);


-- ══════════════════════════════════════════════════════════════
-- 4. STORAGE (bucket Miralocks-media)
-- ⚠️ Créer le bucket manuellement dans :
--    Supabase Dashboard → Storage → New bucket
--    Nom : Miralocks-media  |  Public : ✅
-- ══════════════════════════════════════════════════════════════

DROP POLICY IF EXISTS "lecture_publique_storage" ON storage.objects;
CREATE POLICY "lecture_publique_storage" ON storage.objects
  FOR SELECT USING (bucket_id = 'Miralocks-media');

DROP POLICY IF EXISTS "envoi_publique_rdv" ON storage.objects;
CREATE POLICY "envoi_publique_rdv" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'Miralocks-media'
    AND (storage.foldername(name))[1] = 'rendezvous'
  );

DROP POLICY IF EXISTS "admin_total_storage" ON storage.objects;
CREATE POLICY "admin_total_storage" ON storage.objects
  FOR ALL
  USING (bucket_id = 'Miralocks-media' AND auth.role() = 'authenticated')
  WITH CHECK (bucket_id = 'Miralocks-media' AND auth.role() = 'authenticated');


-- ══════════════════════════════════════════════════════════════
-- 5. ANTI-SPAM (TRIGGERS)
-- ══════════════════════════════════════════════════════════════

-- Avis : max 15 soumissions par heure
CREATE OR REPLACE FUNCTION public.check_avis_limit()
RETURNS TRIGGER AS $$
BEGIN
  IF (
    SELECT count(*) FROM public.avis_clients
    WHERE created_at > NOW() - INTERVAL '1 hour'
  ) >= 15 THEN
    RAISE EXCEPTION 'Trop d''avis soumis. Réessayez plus tard.';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_avis_limit ON public.avis_clients;
CREATE TRIGGER trigger_avis_limit
  BEFORE INSERT ON public.avis_clients
  FOR EACH ROW EXECUTE FUNCTION public.check_avis_limit();

-- Rendez-vous : max 2 demandes par jour par téléphone
CREATE OR REPLACE FUNCTION public.check_rdv_limit()
RETURNS TRIGGER AS $$
BEGIN
  IF (
    SELECT count(*) FROM public.rendezvous
    WHERE tel = NEW.tel AND created_at > NOW() - INTERVAL '1 day'
  ) >= 2 THEN
    RAISE EXCEPTION 'Trop de demandes. Réessayez demain.';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_rdv_limit ON public.rendezvous;
CREATE TRIGGER trigger_rdv_limit
  BEFORE INSERT ON public.rendezvous
  FOR EACH ROW EXECUTE FUNCTION public.check_rdv_limit();


-- ══════════════════════════════════════════════════════════════
-- 6. INDEX (Performances)
-- ══════════════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS idx_visites_date    ON public.visites    (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_visites_page    ON public.visites    (page);
CREATE INDEX IF NOT EXISTS idx_rdv_date        ON public.rendezvous (date_rdv DESC);
CREATE INDEX IF NOT EXISTS idx_rdv_statut      ON public.rendezvous (statut);
CREATE INDEX IF NOT EXISTS idx_services_ord    ON public.services   (ordre ASC);
CREATE INDEX IF NOT EXISTS idx_blog_date       ON public.blog_posts (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_historique_date ON public.historique (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_historique_type ON public.historique (type);


-- ══════════════════════════════════════════════════════════════
-- 7. CRON JOB — Rappels WhatsApp (sécurisé)
-- ══════════════════════════════════════════════════════════════
-- ⚠️  AVANT D'EXÉCUTER : remplace YOUR_SERVICE_ROLE_KEY_HERE
--     par ta clé service_role depuis :
--     Supabase Dashboard → Settings → API → service_role
-- ══════════════════════════════════════════════════════════════

CREATE EXTENSION IF NOT EXISTS pg_cron;

-- Supprimer l'ancien cron s'il existe (sans erreur si absent)
SELECT cron.unschedule(jobid)
FROM cron.job
WHERE jobname = 'rappels-rdv-quotidiens';

-- ⚠️ OBLIGATOIRE : Remplace YOUR_SERVICE_ROLE_KEY_HERE par ta vraie clé
-- Supabase Dashboard → Settings → API → service_role (secret, commence par "eyJ...")
-- Sans cette clé, le cron sera créé mais les rappels WhatsApp ne partiront jamais.
--
-- ❌ NE PAS exécuter ce bloc tant que la clé n'est pas remplacée !
-- Remplace la ligne ci-dessous :
--   'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xaXR5cmlmaGlhYXJ3ZGNhY3hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxMTYwMDEsImV4cCI6MjA4OTY5MjAwMX0.sYsUB9AWPXrsRDnz8YxEQiZOh7USxP2W_QNrZyU3mpE'
-- Par exemple :
--   'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'

SELECT cron.schedule(
  'rappels-rdv-quotidiens',
  '0 8 * * *',
  $$
    SELECT net.http_post(
      url     := 'https://mqityrifhiaarwdcacxo.supabase.co/functions/v1/send-reminders',
      headers := jsonb_build_object(
        'Content-Type',  'application/json',
        'Authorization', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xaXR5cmlmaGlhYXJ3ZGNhY3hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxMTYwMDEsImV4cCI6MjA4OTY5MjAwMX0.sYsUB9AWPXrsRDnz8YxEQiZOh7USxP2W_QNrZyU3mpE'
-- Par exemple :'
      ),
      body    := '{}'::jsonb
    );
  $$
);




-- ══════════════════════════════════════════════════════════════
-- 7b. CRON JOB — Nettoyage automatique codes 2FA expirés
--     Exécuté chaque jour à minuit
-- ══════════════════════════════════════════════════════════════
SELECT cron.unschedule(jobid)
FROM cron.job
WHERE jobname = 'cleanup-2fa-expired';

SELECT cron.schedule(
  'cleanup-2fa-expired',
  '0 0 * * *',
  $$
    DELETE FROM public.admin_2fa
    WHERE used = true
       OR expires_at < NOW();
  $$
);

-- ══════════════════════════════════════════════════════════════
-- 7c. CRON JOB — Nettoyage logs historique (garde 6 mois)
-- ══════════════════════════════════════════════════════════════
SELECT cron.unschedule(jobid)
FROM cron.job
WHERE jobname = 'cleanup-historique-old';

SELECT cron.schedule(
  'cleanup-historique-old',
  '0 1 * * 0',
  $$
    DELETE FROM public.historique
    WHERE created_at < NOW() - INTERVAL '6 months';
  $$
);


-- ══════════════════════════════════════════════════════════════
-- 8. TABLES SUPPLÉMENTAIRES (nouvelles fonctionnalités)
-- ══════════════════════════════════════════════════════════════

-- Table des codes promo (stockée dans site_settings en JSON)
-- Pas de table séparée — gérée via site_settings key='promo_codes'

-- Table suivi RDV : pas de table supplémentaire
-- Le lien est généré côté client avec un hash id+tel

-- ══════════════════════════════════════════════════════════════
-- 7d. CRON JOB — Rappels WhatsApp 24h avant RDV
--     Appelle l'Edge Function send-reminders chaque soir à 20h
--     (les clients reçoivent le rappel la veille au soir)
-- ══════════════════════════════════════════════════════════════
SELECT cron.unschedule(jobid)
FROM cron.job
WHERE jobname = 'rappels-rdv-veille';

-- ⚠️ Remplacer YOUR_SERVICE_ROLE_KEY_HERE par la clé service_role
SELECT cron.schedule(
  'rappels-rdv-veille',
  '0 20 * * *',
  $$
    SELECT net.http_post(
      url     := 'https://mqityrifhiaarwdcacxo.supabase.co/functions/v1/send-reminders',
      headers := jsonb_build_object(
        'Content-Type',  'application/json',
        'Authorization', 'Bearer YOUR_SERVICE_ROLE_KEY_HERE'
      ),
      body    := '{"type":"veille"}'::jsonb
    );
  $$
);

-- ══════════════════════════════════════════════════════════════
-- 9. PARAMÈTRES SUPPLÉMENTAIRES (site_settings)
-- Insérer les clés de configuration par défaut
-- ══════════════════════════════════════════════════════════════

-- 2FA activé (mettre 'true' pour activer)
INSERT INTO public.site_settings (id, valeur) VALUES ('admin_2fa_enabled', 'false')
ON CONFLICT (id) DO NOTHING;

-- Numéro WhatsApp admin pour les alertes de sécurité
INSERT INTO public.site_settings (id, valeur) VALUES ('whatsapp_admin_number', '')
ON CONFLICT (id) DO NOTHING;

-- Rappel auto acompte impayé ('true' pour activer)
INSERT INTO public.site_settings (id, valeur) VALUES ('acompte_auto_reminder', 'false')
ON CONFLICT (id) DO NOTHING;

-- Codes promo (JSON array) — exemple :
-- [{"code":"WELCOME10","label":"10% de bienvenue","reduction":10,"actif":true}]
INSERT INTO public.site_settings (id, valeur) VALUES ('promo_codes', '[]')
ON CONFLICT (id) DO NOTHING;

-- Index supplémentaires pour les nouvelles requêtes
CREATE INDEX IF NOT EXISTS idx_rdv_tel       ON public.rendezvous (tel);
CREATE INDEX IF NOT EXISTS idx_rdv_created   ON public.rendezvous (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_2fa_email     ON public.admin_2fa  (email);
CREATE INDEX IF NOT EXISTS idx_2fa_expires   ON public.admin_2fa  (expires_at);



-- ══════════════════════════════════════════════════════════════
-- 10. TABLES SUPPLÉMENTAIRES v3
-- ══════════════════════════════════════════════════════════════

-- Newsletter abonnés
CREATE TABLE IF NOT EXISTS public.newsletter_abonnes (
  id         BIGSERIAL PRIMARY KEY,
  email      TEXT NOT NULL UNIQUE,
  nom        TEXT,
  actif      BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.newsletter_abonnes ENABLE ROW LEVEL SECURITY;

-- Seul l'admin peut lire, anon peut s'inscrire
GRANT INSERT ON public.newsletter_abonnes TO anon;
GRANT USAGE, SELECT ON SEQUENCE newsletter_abonnes_id_seq TO anon;
GRANT ALL ON public.newsletter_abonnes TO authenticated;

DROP POLICY IF EXISTS "anon_subscribe_newsletter" ON public.newsletter_abonnes;
CREATE POLICY "anon_subscribe_newsletter" ON public.newsletter_abonnes
  FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "admin_all_newsletter" ON public.newsletter_abonnes;
CREATE POLICY "admin_all_newsletter" ON public.newsletter_abonnes
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Index pour email unique
CREATE INDEX IF NOT EXISTS idx_newsletter_email ON public.newsletter_abonnes (email);
CREATE INDEX IF NOT EXISTS idx_newsletter_actif  ON public.newsletter_abonnes (actif);

-- ══════════════════════════════════════════════════════════════
-- 11. PARAMÈTRES SUPPLÉMENTAIRES v3 (site_settings)
-- ══════════════════════════════════════════════════════════════

-- Mode maintenance
INSERT INTO public.site_settings (id, valeur) VALUES ('maintenance_mode', 'false')
ON CONFLICT (id) DO NOTHING;

-- Taux de change devises (JSON: {"EUR":0.00152,"USD":0.00165})
INSERT INTO public.site_settings (id, valeur) VALUES ('currency_rates', '{"EUR":0.00152,"USD":0.00165}')
ON CONFLICT (id) DO NOTHING;

-- Fermetures programmées (JSON array)
INSERT INTO public.site_settings (id, valeur) VALUES ('dates_fermetures', '[]')
ON CONFLICT (id) DO NOTHING;

-- Infos salon pour les factures
INSERT INTO public.site_settings (id, valeur) VALUES ('salon_nom', 'Institut MiraLocks')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.site_settings (id, valeur) VALUES ('salon_adresse', 'Agoè Cacaveli, Lomé, Togo')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.site_settings (id, valeur) VALUES ('salon_tel', '+228 97 98 90 01')
ON CONFLICT (id) DO NOTHING;



-- ══════════════════════════════════════════════════════════════
-- 12. PARAMÈTRES SUPPLÉMENTAIRES v4
-- ══════════════════════════════════════════════════════════════

-- URL vidéo hero (mp4 sur Supabase Storage)
INSERT INTO public.site_settings (id, valeur) VALUES ('hero_video_url', '')
ON CONFLICT (id) DO NOTHING;

-- Africa's Talking SMS
INSERT INTO public.site_settings (id, valeur) VALUES ('africastalking_apikey', '')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.site_settings (id, valeur) VALUES ('africastalking_username', 'sandbox')
ON CONFLICT (id) DO NOTHING;

-- Index pour newsletter
CREATE INDEX IF NOT EXISTS idx_blog_slug    ON public.blog_posts (slug);
CREATE INDEX IF NOT EXISTS idx_blog_publie  ON public.blog_posts (publie, created_at DESC);



-- ══════════════════════════════════════════════════════════════
-- 13. AMÉLIORATIONS TABLES v5
-- ══════════════════════════════════════════════════════════════

-- Ajouter photo_url aux avis clients (pour les avis avec photo)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
    WHERE table_name='avis_clients' AND column_name='photo_url') THEN
    ALTER TABLE public.avis_clients ADD COLUMN photo_url TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
    WHERE table_name='avis_clients' AND column_name='reponse_admin') THEN
    ALTER TABLE public.avis_clients ADD COLUMN reponse_admin TEXT;
  END IF;
END $$;

-- Ajouter photo_avant_url à galerie_photos pour les paires avant/après
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
    WHERE table_name='galerie_photos' AND column_name='photo_avant_url') THEN
    ALTER TABLE public.galerie_photos ADD COLUMN photo_avant_url TEXT;
  END IF;
END $$;

-- Index supplémentaires
CREATE INDEX IF NOT EXISTS idx_galerie_categorie ON public.galerie_photos (categorie);
CREATE INDEX IF NOT EXISTS idx_avis_approuve     ON public.avis_clients  (approuve, created_at DESC);

-- Anon peut uploader une photo dans le dossier avis
DROP POLICY IF EXISTS "envoi_publique_avis" ON storage.objects;
CREATE POLICY "envoi_publique_avis" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'Miralocks-media'
    AND (storage.foldername(name))[1] = 'avis'
  );


-- ══════════════════════════════════════════════════════════════
-- ✅ VÉRIFICATION FINALE
-- Exécute cette requête séparément pour voir toutes les policies :
-- ══════════════════════════════════════════════════════════════
/*
SELECT tablename, policyname, roles, cmd
FROM pg_policies
WHERE schemaname = 'public'
ORDER BY tablename, policyname;
*/

-- ============================================================
--  RÉSUMÉ DE SÉCURITÉ
-- ============================================================
--  Table          | Accès anon
--  ---------------|------------------------------------------
--  settings       | ❌ Aucun (clés API protégées)
--  site_settings  | ✅ Lecture partielle (whitelist)
--  rendezvous     | ✅ INSERT seulement (pas de lecture)
--  admin_2fa      | ❌ Aucun (RLS activé)
--  historique     | ❌ Aucun
--  admin_logs     | ❌ Aucun
--  blog_posts     | ✅ SELECT (publie = true)
--  galerie_photos | ✅ SELECT (publie = true)
--  services       | ✅ SELECT (tous)
--  avis_clients   | ✅ SELECT (approuve) + INSERT
--  visites        | ✅ INSERT seulement
-- ============================================================
